Admin page
AI-Global/ai-portal pull request #13
Opened 2020-10-20 22:38 UTC by cphillips17

Added updates to the admin page

2020-10-21 22:25 UTC, sshh12 requested changes
Look great, just some super small stuff.

2020-10-21 22:25 UTC, sshh12 commented on src/views/Admin.js
> +              {/* <Menu.Item>
Can you remove these sections of commented code

2020-10-21 22:25 UTC, sshh12 commented on src/views/Admin.js
> +          <Card id="overview" style={{ marginBottom: '20px' }}>
Can you turn theses Cards into their own subcomponents (you can keep them in the same file).

It'll make the JSX a bit more readable and make it the code just a bit more reusable.

2020-10-21 22:25 UTC, sshh12 commented on src/views/Admin.js
> +  { name: 'The A-Z of AI', logoURL: '/demo/theazlogo.png' },
I'm not sure which one of these you are using, but go ahead and delete any unused imports here & probably TEMP_FRONTEND_ITEMS

2020-10-22 06:37 UTC, cphillips17 commented
Made updates and some changes - going to treat tabs on left as scrollable buttons to go to relevant section. I used raw values rather than refs to scroll, will update later.

2020-10-26 14:09 UTC, sshh12 approved these changes
LGTM

2020-10-26 14:09 UTC, merged