Add form at /resources/create
AI-Global/ai-portal pull request #15
Opened 2020-10-23 03:34 UTC by lucindan

-Used header from Resources Page
-Most fields are multi-select (except technical/non-technical)

2020-10-26 14:23 UTC, sshh12 requested changes
Looks great, just a few changes.

A cool bonus thing to add would be subtext next to all the options for explaining what things are. E.g. next to Name Of Resource we have small text that says "This is what your resource will be displayed as, make sure capitalization and spelling is correct". You could use filler text for now rather than writing this for every option.

Also can we center and trim this:
<img width="1230" alt="chrome_mmNRlTIvdh" src="https://user-images.githubusercontent.com/6625384/97183927-55e65f80-176c-11eb-9ec1-8c7f3760d5a5.png">

2020-10-26 14:23 UTC, sshh12 commented on src/App.js
> +import addResources from './views/AddResource'
Can you make this `AddResources `. Also, there's a small merge conflict here, lmk if you need help resolving it.

2020-10-26 14:23 UTC, sshh12 commented on src/App.js
> +            </Route>
Can you make this:
```
<Route exact path="/resources" component={Resources} />
<Route exact path="/resources/create" component={AddResources} />
```

2020-10-26 14:23 UTC, sshh12 commented on src/components/ResourceField.js
> +const {Option} = Select;
This should be:
```
import {
  Form,
  Select,
} from '../ant';
const {Option} = Select;
```

2020-10-26 14:23 UTC, sshh12 commented on src/components/ResourceField.js
> +const {Option} = Select;
The reasoning behind this is that we are using `../ant` rather than `antd` to make some import statements easier in the long run.

2020-10-26 14:23 UTC, sshh12 commented on src/views/AddResource.js
> +import {Typography,  DatePicker} from 'antd'
Same as the above, import Typography & DatePicker from `../ant`. You may also need to add them to the `../ant` file.

2020-10-28 02:17 UTC, lucindan commented
Made changes requested (center and trim form, fixed imports, and added a popup text for each field to describe what to input)
Fix merge conflict.

2020-10-29 14:59 UTC, sshh12 requested changes
Tooltips look great. Looks like there's still some rendering weirdness:
<img width="1283" alt="chrome_XKlhc4Cdxc" src="https://user-images.githubusercontent.com/6625384/97591202-5e89a080-19cd-11eb-9cc0-1f82b457b1ce.png">

2020-10-29 15:08 UTC, sshh12 commented
Also, see comments from https://github.com/AI-Global/ai-portal/pull/18

2020-10-30 06:27 UTC, lucindan commented
-Fixed centering
-Added Header as component
-Renamed

2020-11-02 22:38 UTC, merged