Lucinda/view resource
AI-Global/ai-portal pull request #26
Opened 2020-11-13 23:02 UTC by lucindan

-Using Montreal AI Ethics' Living Dictionary as an example
-Using same menu as "Admin page"
-Broken into description, details, and files

2020-11-14 20:24 UTC, sshh12 commented
FYI @Marthacz you can review this page when merged at /resources/example

2020-11-14 20:32 UTC, sshh12 requested changes
Looks good, some small tweaks.

Also there seems to be a lot of little formatting things. Make sure you have the `esbenp.prettier-vscode` vscode plugin and format these (this plugin will auto format whenever you save the file)

2020-11-14 20:32 UTC, sshh12 commented on src/App.js
> +import ResourceInfo from './views/ResourceInfo';
Can we make this "ViewResource", this will match our existing view naming,

2020-11-14 20:32 UTC, sshh12 commented on src/views/ResourceInfo.js
> +function ResourceInfo(props) {
"ViewResource". Also is what should be exported (you can prob delete ShowExample and just define the resource example data inside the component).

2020-11-14 20:32 UTC, sshh12 commented on src/views/ResourceInfo.js
> +          <div ref={detailRef}>
Can we add more padding to the left and right of this component. Right now it's flush with the sides but there should be a small gap.

2020-11-14 20:55 UTC, Marthacz commented
> FYI @Marthacz you can review this page when merged at /resources/example

Thanks! I'll review once merged.

2020-11-14 22:35 UTC, lucindan commented
-Renamed to ViewResource
-Added padding

2020-11-16 17:33 UTC, sshh12 approved these changes

2020-11-16 17:33 UTC, merged