update create account with original template
AI-Global/ai-portal pull request #34
Opened 2020-11-18 05:09 UTC by Marthacz

Template: https://docs.google.com/document/d/1MCGk8TZpo9d7nncStZbRMbPAdmPeLNSTsUnzZvEkegg/ed

2020-11-18 05:10 UTC, Marthacz commented
We need to add Thanks, AI Global Team with a space? How would that work?

2020-11-18 15:52 UTC, sshh12 requested changes

2020-11-18 15:52 UTC, sshh12 commented on api/lib/emails/createAccount.email.js
> +    To complete the registration, please verify your email${verifyUrl}`;
missing space here

2020-11-19 17:44 UTC, sshh12 approved these changes

2020-11-19 17:44 UTC, merged