Lucinda/resources
AI-Global/ai-portal pull request #48
Opened 2020-11-27 07:54 UTC by lucindan

-changed links on the modal for /resources to go to /resources/<id>
-added API method to search by resource._id

2020-11-28 17:52 UTC, sshh12 requested changes
Some rly small tweaks

2020-11-28 17:52 UTC, sshh12 commented on api/routes/resource.routes.js
> +
Thanks for adding these!

2020-11-28 17:52 UTC, sshh12 commented on src/views/ViewResource.js
> +const emptyRes = {
can you remove everything that we no longer need here

2020-11-28 17:52 UTC, sshh12 commented on src/views/ViewResource.js
> +  let [resource, setResource] = useState(emptyRes);
can we make this default to null (rather than empty res) and then just render a spinner if it hasn't loaded yet

2020-12-10 21:10 UTC, lucindan commented
spinner while loading

2020-12-10 23:03 UTC, sshh12 approved these changes

2020-12-10 23:03 UTC, merged