Filtering
AI-Global/ai-portal pull request #62
Opened 2021-01-10 03:52 UTC by cphillips17

Added the filtering - editing the landing and adding an FAQ view (in progress)

2021-01-10 16:43 UTC, sshh12 requested changes
Looks good, small tweaks.

2021-01-10 16:43 UTC, sshh12 commented on src/views/Landing.js
> +  };
This should also include a call to `setVisited(true)` (need to update both localstorage as well as already loaded state)

2021-01-10 16:43 UTC, sshh12 commented on src/views/Landing.js
> +    setVisited(true);
Everywhere (except inside setLSHasVisited) should call setLSHasVisited

2021-01-10 16:49 UTC, sshh12 commented
May help to component-ize some of the duplicated parts of landing page.

2021-01-11 02:18 UTC, cphillips17 commented
Made the edits - for openNotification, the modal did not open if setLSHasVisited is called, will debug

2021-01-18 15:58 UTC, sshh12 commented
Merging so this PR doesn't block.

2021-01-18 15:59 UTC, merged